   version: 0.2

   phases:
     build:
       commands:
         - echo Build started on `date`
         - echo No build commands needed for static site
     post_build:
       commands:
         - echo Build completed on `date`
   artifacts:
     files:
       - '**/*'